version: '3.8'

services:
  db-dev:
    image: postgres:15
    container_name: farmacia-db-dev
    environment:
      POSTGRES_DB: farmacia_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - farmacia-network-dev

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: farmacia-backend-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://admin:${DB_PASSWORD}@db-dev:5432/farmacia_dev
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3001
      FRONTEND_URL: https://develop.diegolima.dev/farmacia
    ports:
      - "3001:3001"
    depends_on:
      - db-dev
    networks:
      - farmacia-network-dev

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: farmacia-frontend-dev
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: /farmacia/api
      REACT_APP_BACKEND_URL: http://backend-dev:3001
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    depends_on:
      - backend-dev
    networks:
      - farmacia-network-dev

volumes:
  postgres_data_dev:

networks:
  farmacia-network-dev:
    driver: bridge