# Docker Compose - Arquitetura Microserviços Farmácia
version: '3.8'

services:
  # Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: farmacia-db
    environment:
      POSTGRES_DB: farmacia_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farmacia-net
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: farmacia-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://admin:dev123456@db:5432/farmacia_dev
      JWT_SECRET: sua-chave-secreta-muito-segura-aqui-com-pelo-menos-32-caracteres
      PORT: 3001
    depends_on:
      - db
    networks:
      - farmacia-net
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  # Frontend React + Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: farmacia-frontend
    networks:
      - farmacia-net
    restart: unless-stopped

  # Nginx Proxy Reverso
  proxy:
    image: nginx:alpine
    container_name: farmacia-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - farmacia-net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  farmacia-net:
    driver: bridge