# Docker Compose Simples - Apenas Backend para Coolify
version: '3.8'

services:
  # Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: farmacia-db
    environment:
      POSTGRES_DB: farmacia_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farmacia-net
    restart: unless-stopped

  # Backend API (sem proxy)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farmacia-backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://admin:dev123456@db:5432/farmacia_dev
      JWT_SECRET: sua-chave-secreta-muito-segura-aqui-com-pelo-menos-32-caracteres
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - farmacia-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:

networks:
  farmacia-net:
    driver: bridge